name: Sunset Telegram Bot Run Action

on:
  workflow_dispatch:     # Optional: allows manual triggering
  schedule:
    - cron: '0 14 * * *' # Runs daily at 14:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Cron job run"
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run sunset bot
        env:
          SUNSETHUE_API_KEY: ${{ secrets.SUNSETHUE_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          python sunset_bot.py
